# Generated by Django 3.2.5 on 2021-09-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cryptocurrency_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_base', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cryptocurrency_quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_quote', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cryptoexchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchanges', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('available_exchanges', models.CharField(max_length=200)),
                ('currency_base', models.CharField(max_length=200)),
                ('currency_quote', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='forexcurrency_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_base', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='forexcurrency_quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_quote', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ForexTickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('currency_group', models.CharField(max_length=200)),
                ('currency_base', models.CharField(max_length=200)),
                ('currency_quote', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='indexcountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='indexcurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IndexTickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StockTickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='USIndexTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='USStockTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IndexList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ManyToManyField(to='PBSTAPP.indexcountries')),
                ('currency', models.ManyToManyField(to='PBSTAPP.indexcurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Forexlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('currency_group', models.CharField(max_length=100)),
                ('currency_base', models.ManyToManyField(to='PBSTAPP.forexcurrency_base')),
                ('currency_quote', models.ManyToManyField(to='PBSTAPP.forexcurrency_quote')),
            ],
        ),
        migrations.CreateModel(
            name='cryptolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('available_exchanges', models.ManyToManyField(blank=True, to='PBSTAPP.cryptoexchanges')),
                ('currency_base', models.ManyToManyField(blank=True, to='PBSTAPP.cryptocurrency_base')),
                ('currency_quote', models.ManyToManyField(blank=True, to='PBSTAPP.cryptocurrency_quote')),
            ],
        ),
    ]
