# Generated by Django 3.2.5 on 2021-10-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBSTAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptolist',
            name='available_exchanges',
        ),
        migrations.RemoveField(
            model_name='cryptolist',
            name='currency_base',
        ),
        migrations.RemoveField(
            model_name='cryptolist',
            name='currency_quote',
        ),
        migrations.RemoveField(
            model_name='forexlist',
            name='currency_base',
        ),
        migrations.RemoveField(
            model_name='forexlist',
            name='currency_quote',
        ),
        migrations.RemoveField(
            model_name='indexlist',
            name='country',
        ),
        migrations.RemoveField(
            model_name='indexlist',
            name='currency',
        ),
        migrations.DeleteModel(
            name='cryptocurrency_base',
        ),
        migrations.DeleteModel(
            name='cryptocurrency_quote',
        ),
        migrations.DeleteModel(
            name='cryptoexchanges',
        ),
        migrations.DeleteModel(
            name='cryptolist',
        ),
        migrations.DeleteModel(
            name='forexcurrency_base',
        ),
        migrations.DeleteModel(
            name='forexcurrency_quote',
        ),
        migrations.DeleteModel(
            name='Forexlist',
        ),
        migrations.DeleteModel(
            name='indexcountries',
        ),
        migrations.DeleteModel(
            name='indexcurrency',
        ),
        migrations.DeleteModel(
            name='IndexList',
        ),
    ]
